import '@/styles/globals.css'
import { inter } from '@/fonts'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} layout-sen-doan`}>{children}</body>
    </html>
  )
}
